# Generated by Django 4.0 on 2022-01-11 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subauthor',
            old_name='author',
            new_name='author2',
        ),
        migrations.RenameField(
            model_name='subauthor',
            old_name='category',
            new_name='category2',
        ),
    ]
