# Generated by Django 4.0 on 2022-01-24 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_postcategory_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subauthor',
            old_name='author2',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='subauthor',
            old_name='category2',
            new_name='category',
        ),
    ]
