# Generated by Django 4.0 on 2022-01-24 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_rename_author2_subauthor_author_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subauthor',
            old_name='author',
            new_name='subaut',
        ),
        migrations.RenameField(
            model_name='subauthor',
            old_name='category',
            new_name='subcat',
        ),
        migrations.AlterField(
            model_name='author',
            name='subscribers',
            field=models.ManyToManyField(through='news.SubAuthor', to='news.Category', verbose_name='Подписка'),
        ),
    ]
